Example config with caddy, ready to run
LycheeOrg/Lychee-Docker pull request #212
Opened 2024-12-20 13:01 UTC by tinohager

with automatic Let's Encrypt integration

2024-12-20 13:16 UTC, d7415 commented
I don't really see the benefit here. It's not sufficient for upstream as there's no TLS handling (unless Caddy automatically handles that - it's been a while). It seems to just be adding an extra layer.

2024-12-20 23:38 UTC, tinohager commented
*   Zero-Configuration HTTPS: With Caddy, simply specifying your domain in the Caddyfile triggers automatic HTTPS with Let's Encrypt. There’s no need to deal with the cumbersome details of SSL setup.

  *   Automatic Renewal: Caddy automatically renews your certificates before they expire. This means you can keep your website secure without having to track or manually update SSL certificates.

2024-12-21 15:53 UTC, ildyria requested changes

2024-12-25 16:08 UTC, ildyria approved these changes

2024-12-26 18:01 UTC, merged